variable name {
  type        = string
  description = "The name of the Auto Scaling Group. By default generated by Terraform. Conflicts with name_prefix"
}

variable max_size {
  type        = number
  default     = 2
  description = "The maximum size of the Auto Scaling Group."
}

variable min_size {
  type        = number
  default     = 1
  description = "The minimum size of the Auto Scaling Group."
}

variable force_delete {
  type        = bool
  default     = false
  description = "Allows deleting the Auto Scaling Group without waiting for all instances in the pool to terminate. You can force an Auto Scaling Group to delete even if it's in the process of scaling a resource. Normally, Terraform drains all the instances before deleting the group. This bypasses that behavior and potentially leaves resources dangling."
}

variable desired_capacity {
  type        = number
  default     = 1
  description = "The number of Amazon EC2 instances that should be running in the group."
}

variable subnets {
  type        = list(string)
  default     = []
  description = " A list of subnet IDs to launch resources in. Subnets automatically determine which availability zones the group will reside. Conflicts with availability_zones"
}

variable health_check_type {
  type = string
  default = "EC2"
  description = "'EC2' or 'ELB'. Controls how health checking is done."
}

//----------------------------------------------------------------------
// Launch Configuration Variables
//----------------------------------------------------------------------

variable image_id {
  type = string
  description = "The name for the autoscaling group for the cluster."
  default = "ami-001085c9389955bb6"
}

variable user_data {
  type = string
  description = "User data for new instances launching with this configuration"
  default = ""
}

variable iam_instance_profile_name {
  type = string
  description = "The name attribute of the IAM instance profile to associate with launched instances."
  default = "ami-001085c9389955bb6"
}

variable instance_type {
  type = string
  description = "The size of instance to launch."
  default = "t2.small"
}

variable associate_public_ip_address {
  type = bool
  description = "Associate a public ip address with an instance in a VPC."
  default = false
}

variable security_groups {
  type        = list(string)
  default     = []
  description = "A list of security group IDs to assign to the LB. Only valid for Load Balancers of type Application"
}

variable key_name {
  type = string
  default = ""
  description = "The key name that should be used for the instance."
}