name: 'IAM OIDC Provider Module CI'

on:
  push:
    paths:
      - modules/iam-oidc-provider/**

defaults:
  run:
    shell: bash
    working-directory: modules/iam-oidc-provider/

jobs:
  lint:
    name: lint
    uses: kolvin/github-actions/.github/workflows/terraform-module-lint.yaml@8981afdb7157ca6ea767a28a06696e3a2a30ee86