name: 'Module CI'

on: push

defaults:
  run:
    shell: bash
    working-directory: modules/iam-role/

jobs:
  lint:
    uses: kolvin/github-actions/.github/workflows/terraform-module-lint.yaml@576ddacee730872ee7f42311fa99465fa65bd9b7