name: 'Service: nginx-ecs-asg-alb'

on: push
    # paths:
    #   - kloud/dev/eu-west-1/nginx-ecs-asg-alb/**

env:
  AWS_ACCOUNT_ID: "016272825626"
  AWS_REGION: "eu-west-1"

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: kloud/dev/eu-west-1/nginx-ecs-asg-alb

jobs:
  name: setup
  uses: kolvin/github-actions/.github/workflows/terragrunt-setup.yaml@02b600bf7d082892a0a95cc40c79d908229ef516
  name: lint
  uses: kolvin/github-actions/.github/workflows/terragrunt-lint.yaml@02b600bf7d082892a0a95cc40c79d908229ef516
  name: plan
  uses: kolvin/github-actions/.github/workflows/terragrunt-plan.yaml@02b600bf7d082892a0a95cc40c79d908229ef516
  name: apply
  uses: kolvin/github-actions/.github/workflows/terragrunt-apply.yaml@8e218b735a189a49716a3c8cad4e922e501ff3d0