name: 'Terragrunt CI/CD'

on: push

env:
  AWS_ACCOUNT_ID : "016272825626"
  AWS_REGION : "eu-west-1"

permissions:
  id-token: write
  contents: read

jobs:
  terragrunt:
    runs-on: ubuntu-latest
    steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/terragrunt-github-ci
        role-session-name: terragrunt-ci
        aws-region: ${{ env.AWS_REGION }}
    - uses: actions/checkout@v1
    - name: Setup Terraform & Terragrunt
      run: |
        brew install tfenv warrensbox/tap/tgswitch
        tfenv install
        tgswitch
    
