name: 'Module Formating and Validation'

on:
  push:
    paths:
      - modules/iam-role

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Terraform & Terragrunt
      run: |
        brew install tfenv
        tfenv install
    - name: terraform fmt
      run: |
        terraform fmt -check
