name: 'Terragrunt CI/CD'

on:
  push:
    branches:
      - main

jobs:
  terragrunt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Terraform & Terragrunt
      run: |
        brew install tfenv warrensbox/tap/tgswitch
        tfenv use
        tgswitch
    
